spring:
  profiles:
    active:
      - dev
  data:
    web:
      pageable:
        max-page-size: 100
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  datasource:
    generate-unique-name: false
  h2:
    console:
      enabled: true
      path: /h2
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:./dwitter-prod
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
dwitter:
  uploadPath: uploads-prod
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:dwitter-dev
dwitter:
  uploadPath: uploads-dev
---
spring:
  profiles: test
dwitter:
  uploadPath: uploads-test